language: node_js
node_js:
- 12
os:
- linux
- osx
- windows
cache:
  directories:
  - node_modules
git:
  autocrlf: input
script:
- yarn lint
- yarn flow
- flow stop
- yarn test --coverage
- yarn build
- yarn run bundlesize
- yarn esdoc && mv docs/ build/
after_script:
- if [ "x$TRAVIS_OS_NAME" = "xlinux" -a "x$TRAVIS_BRANCH" = "xmaster" ]; then
    yarn coveralls;
  else true; fi
- if [ "x$TRAVIS_OS_NAME" = "xlinux" ]; then
    yarn snapshot;
  fi
matrix:
  allow_failures:
  - os: windows
  fast_finish: true
