language: node_js

node_js:
- stable

os:
- linux
- osx
- windows

cache:
  directories:
  - node_modules

script:
- yarn lint
- yarn flow
- yarn test
- yarn build

jobs:
  include:
    - stage: deploy
      provider: surge
      skip_cleanup: true
      project: ./build/
      domain: relational-playground.surge.sh  
      on:
        branch: master
      os: linux
      node_js: stable
