language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn lint
- yarn flow
- yarn test
- yarn build
deploy:
  provider: surge
  skip_cleanup: true
  project: ./build/
  domain: relational-playground.surge.sh  
  on:
    branch: master
