language: node_js
node_js:
- 12
os:
- linux
- osx
- windows
cache:
  directories:
  - node_modules
git:
  autocrlf: input
script:
- yarn lint
- yarn flow
- flow stop
- yarn test --coverage
- yarn build
- yarn run bundlesize
- yarn esdoc && mv docs/ build/
- gpgconf --kill gpg-agent
after_script:
- if [ "x$TRAVIS_OS_NAME" = "xlinux" -a "x$TRAVIS_BRANCH" = "xmain" ]; then
    yarn coveralls;
  else true; fi
- if [ "x$TRAVIS_OS_NAME" = "xlinux" ]; then
    yarn snapshot;

    if [[ $TRAVIS_EVENT_TYPE != "pull_request" || $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]]; then
      if [ "x$TRAVIS_BRANCH" = "xmain" ]; then
        yarn chromatic --auto-accept-changes;
      else
        yarn chromatic --exit-zero-on-changes;
      fi
    fi
  fi
