name: CI
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'

      - run: yarn install
      - run: yarn lint
      - run: yarn flow
      - run: yarn test --coverage
      - run: yarn build
      - run: yarn run bundlesize
      - run: yarn esdoc

      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        if: ${{ matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/main' }}
        run: yarn coveralls
        shell: bash

      - name: Publish to Chromatic
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: main
          exitZeroOnChanges: true
          exitOnceUploaded: true
