on: push
name: Lint
jobs:
  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Dependencies
      uses: actions/npm@master
      with:
        args: install
    - name: Eslint
      uses: docker://rkusa/eslint-action:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
